### ISSUE TITLE
Many2Many are not reflecting correctly in Odoo. 

### ISSUE THREAD

**Issue by Msoyosa** [Jack-Dane/odoo-wp-plugin#38]
As a [person], 

I [want to], 

[so that].

**Comment by Jack-Dane** [comment]
> Hi Jack, thank you for your plugin for CF7 integration with Odoo. Can I ask how to include the company name and marketing tag, the marketing tag has a Odoo field name "x_studio_marketing_tag" - many to many. They are not reflecting in Odoo, both the company name and marketing tag. Thank you.

Hi @Msoyosa, 

Have you seen this [example](https://github.com/Jack-Dane/odoo-wp-plugin/blob/main/examples/relational_fields.md#many2many-and-one2many)?

This should explain how to get a Many2Many field mapping correct for tags, you should be able to follow the same principles for your custom field.

**Comment by Msoyosa** [comment]
Hi Jack yes, I already saw this, but the company is an input field and the marketing tag is a constant value, in this example it's talked about the dropdown field

**Comment by Jack-Dane** [comment]
> the marketing tag is a constant value

his should be simple enough, you should just be able to use the IDs for the constant value, so your constant value would be: 
 `1,2,3`

There is an example for a [constant value M2M field](https://github.com/Jack-Dane/odoo-wp-plugin/blob/main/examples/relational_fields.md#with-constant-tags). 

> the company is an input field

If by "input field" you mean a text field, I don't see how this would ever work. What if a user entered a company that didn't exist in Odoo, how would you expect the form to handle it? 

A drop-down field (or some sort of pre-defined list) is needed because it needs to map the ID from that field to a company that exists within Odoo.

**Comment by Jack-Dane** [comment]
Closed due to inactivity.
