### ISSUE TITLE
Odoo Form Mappings and Odoo Connections not working

### ISSUE THREAD

**Issue by JulesNdanga** [Jack-Dane/odoo-wp-plugin#5]
The buttons create a new connection for odoo and create a new mapping do not work. This does not open a form, as in the video tutorial. I'm on wordpress 6.2.2 and php 8.2.

**Comment by JulesNdanga** [comment]
I notice in odoo_form_mapping.php file at line 6 where there is '/odoo_conn/admin/pages/odoo_form_mapping.js'
Why did you put odoo_conn, when its file does not exist? There is an odoo_conn.php file, but no odoo_conn folder. If it's the road, where do you declare that?

**Comment by Jack-Dane** [comment]
Hi @JulesNdanga, thanks for opening this issue. 

I think the problem here is related to the browser. Could you let me know the browser name and version please? Also do you see any errors in your browser debugging window?

> Why did you put odoo_conn, when its file does not exist? 
The plugins URL relates not to the file system, but to the plugin URL. I believe WP uses `odoo_conn` in this case because it is the name of the main file (the file you noted). 

This is the raw output of `plugins_url` on my local instance for example: `http://localhost:8080/wp-content/plugins`.

**Comment by Jack-Dane** [comment]
I can actually see this issue when clearing the Chrome cache on my browser. 

@JulesNdanga it looks like you were correct, although it is a URL it is based on the file system, I will get this changed to not depend on the static string. I am sure there is a better way of implementing this.

**Comment by Jack-Dane** [comment]
@JulesNdanga, I have merged a pull request that should fix the issue, let me know if all is good and if this ticket can be closed.

**Comment by JulesNdanga** [comment]
Yes, problem solved, thank you.
